import { Sidebar } from "@/src/components/Sidebar";
import { Inter } from "next/font/google";
import "./globals.css";
import "./vars.css";
import { NextAuthProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <div
            id="app"
            className="grid lg:grid-cols-[var(--sidebar-width),1fr] lg:min-h-screen"
          >
            <Sidebar />
            <main className="flex-grow">{children}</main>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
