import { Sidebar } from "@/src/components/Sidebar";
import { Inter } from "next/font/google";
import "./globals.css";
import "./vars.css";
import "../app/css/popover.css";
import "../app/css/addNewCard.css";
import { NextAuthProvider } from "./providers";
import QueryWrapper from "./query-wrapper";
import { getServerSession } from "next-auth";
import { authOptions } from "@/src/auth/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider token={session?.user.accessToken ?? ""}>
          <QueryWrapper>
            <div
              id="app"
              className="grid lg:grid-cols-[var(--sidebar-width),1fr] lg:min-h-screen"
            >
              <Sidebar />
              <main className="flex-grow">{children}</main>
            </div>
          </QueryWrapper>
        </NextAuthProvider>
      </body>
    </html>
  );
}
